#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 180

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "mENZV/yo9pXl"
#define LAYER_STATE_8BIT

#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define AUTO_MOUSE_TIME 600
#define NAVIGATOR_SCROLL_INVERT
#define NAVIGATOR_SCROLL_DIVIDER 24 
#define RGB_MATRIX_STARTUP_SPD 60

