#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 170

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "mENZV/40OeWQ"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
