#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "rAljw/nl6y3D"
#define LAYER_STATE_8BIT

#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define NAVIGATOR_SCROLL_DIVIDER 24
#define RGB_MATRIX_STARTUP_SPD 60

