#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 180

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 50

#define SERIAL_NUMBER "zrAwJ/yooLRn"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
